server:
  port: 8086

spring:
    datasource:
            name: test
            url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8
            username: root
            password: root
#            driver-class-name: com.mysql.cj.jdbc.Driver
            driver-class-name: com.mysql.jdbc.Driver
#            #最大活跃数
#            maxActive: 40
#            #初始连接数
#            initialSize: 10
#            #最长等待时间(毫秒)
#            maxWait: 60000
#            #最小idle数（空闲
#            minIdle: 5
#            #some positive integer
#            timeBetweenEvictionRunsMillis: 60000
#            #set to something smaller than 'wait_timeout'
#            minEvictableIdleTimeMillis: 300000
#            #No operations allowed after connection closed\u9519\u8BEF
#            validationQuery: select 'x'
#            testWhileIdle: true
#            #if you don't mind a hit for every getConnection(), set to "true"
#            testOnBorrow: true
#            testOnReturn: false
#            poolPreparedStatements: true
#            maxOpenPreparedStatements: 20

mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    # 下划线形式自动转为驼峰命名
    configuration:
        mapUnderscoreToCamelCas: true

